config/routes.rb
Rails.application.routes.draw do

  root "library#list"
  get "checkout" => "library#new_checkout"
  post "checkout" => "library#checkout"

  get "checkin" => "library#new_checkin"
  post "checkin" => "library#checkin"

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :checkouts
  has_many :books, through: :checkouts
end

app/models/checkout.rb
class Checkout < ActiveRecord::Base
  belongs_to :book
  belongs_to :patron

  def checked_out?
    checked_in_at.nil?
  end
end

app/models/patron.rb
class Patron < ActiveRecord::Base
  has_many :checkouts
  has_many :books, through: :checkouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/library_controller.rb
class LibraryController < ApplicationController
  def list
    @books = Book.all
    @patrons = Patron.all
  end

  def new_checkout
    @checkout = Checkout.new
    if params[:book_id]
      @checkout.book  = Book.find(params[:book_id])
    end
  end

  def checkout
    @checkout = Checkout.new(params.require(:checkout).permit(:book_id, :patron_id))
    @checkout.checked_out_at = DateTime.now
    if @checkout.save
      @checkout.book.available = false
      @checkout.book.save
      redirect_to root_path, notice: "#{@checkout.book.title} has been checked out of the library"
    else
      render :new_checkout
    end
  end

  def new_checkin
    @checkouts = Checkout.where("checked_in_at IS NULL")
  end

  def checkin
    @checkout = Checkout.find(params[:checkout_id])
    @checkout.checked_in_at = DateTime.now
    if @checkout.save!
      @checkout.book.update(available: true)
      redirect_to root_path, notice: "#{@checkout.book.title} has been checked in"
    else
      render :new_checkin
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jlibrary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/library/list.html.erb
<h1>Library</h1>

<div>
  <%= link_to "Check in a Book", checkin_path %>
</div>

<% @books.each do |book| %>
  <li>
    <strong><%= book.title %></strong> by
    <em><%= book.author %></em>
    <%= book.year %>.
    <% if book.available? %>
      <%= link_to "Checkout", checkout_path(book_id: book.id) %>
    <% end %>
  </li>
<% end %>


<% @patrons.each do |patron| %>
  <h2><%= patron.name %></h2>
  <p>Currently checked out:</p>
  <% patron.checkouts.select {|checkout| checkout.checked_out?}.each do |checkout| %>
    <li><%= checkout.book.title %></li>
  <% end %>
  <p>History of read books:</p>
  <% patron.books.each do |book| %>
    <li><%= book.title%> by <%= book.author %></li>
  <% end %>
<% end %>

app/views/library/new_checkin.html.erb
<h1>Check in a Book</h1>

Steps:

<ol>
  <li>View all books checked-out</li>
  <li>Click check-in on that</li>
  <li>That will check in that book</li>
</ol>

<% @checkouts.each do |checkout| %>
  <li>
    <%= checkout.book.title %>. Checked Out by <%= checkout.patron.name %>  <%= distance_of_time_in_words checkout.checked_out_at, Time.now %> ago.
    <%= link_to "Check-in", checkin_path(checkout_id: checkout.id), method: :post, data: {confirm: "Check in #{checkout.book.title}?"} %>

  </li>
<% end %>

app/views/library/new_checkout.html.erb
<h1>Library#new_checkout</h1>


<%= form_for @checkout, url: checkout_path do |f| %>
  <div>
    <%= f.label :book %>
    <%= f.collection_select :book_id, Book.all, :id, :title, prompt: true %>
  </div>
  <div>
    <%= f.label :patron %>
    <%= f.collection_select :patron_id, Patron.all, :id, :name, prompt: true %>
  </div>
  <div>
    <%= f.submit "Checkout Book" %>
  </div>
<% end %>